version: 2.1
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - setup_remote_docker
            
            - run:
                name: 'Verify code is checked out'    
                command: ls -al            
            - run:
                name: 'Install Packages'
                command: yarn install
            - run: 
                name: 'Build application'
                command: yarn build
            - run:
                name: 'Build docker tag for Azure'                
                command: |
                    docker build -t vasanthapuram.azurecr.io/retail:1.0
            - run :
                name: 'Provide azure login/pass information to circleci'
                command: | 
                    docker login --username $DOCKER_USER --password $DOCKER_PASS vasanthapuram.azurecr.io
            - run:
                name: 'Push docker image to azure container registry'
                command: |
                    docker push vasanthapuram.azurecr.io/retail:1.0
            
                